mapcar (LISP like) code is almost complete but still untested due to a compilation error.
[ERROR]
/media/disk1part6/develop/Projects/WikiModels/workspace/wikimodels/UsefullScalaStuff/src/main/scala/alexmsmartins/list/MapFuncitons.scala:35:
error: type mismatch;
[INFO]  found   : Unit
[INFO]  required: List[T]
[INFO]     for (val index <- List.range(0
(lists.head).asInstanceOf[List[T]].size).asInstanceOf[List[Int]]  ) {
[INFO]                    ^
[ERROR]
/media/disk1part6/develop/Projects/WikiModels/workspace/wikimodels/UsefullScalaStuff/src/main/scala/alexmsmartins/list/MapFuncitons.scala:42:
error: type mismatch;
[INFO]  found   : Unit
[INFO]  required: List[T]
[INFO]     for (val index <- List.range(0
lists.head.asInstanceOf[List[T]].size).asInstanceOf[List[Int]]  ) {
[INFO]                    ^
[ERROR]
/media/disk1part6/develop/Projects/WikiModels/workspace/wikimodels/UsefullScalaStuff/src/main/scala/alexmsmartins/list/MapFuncitons.scala:49:
error: type mismatch;
[INFO]  found   : Unit
[INFO]  required: List[T]
[INFO]     for (val index <- List.range(0
lists.head.asInstanceOf[List[T]].size).asInstanceOf[List[Int]]  ) {
[INFO]                    ^